### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by AMCN41R**
Updated `README.md` formatting and content to improve readability.

### CODE REVIEW

**Comment by AMCN41R** [comment]
Hey @SLdragon, wondered if you could help me with this one (or reject if you're not happy).

This PR just updates the `README.md`, but both python builds are failing with similar errors...

#### 2.7
```
______________________ ERROR collecting tests/test_cli.py ______________________
tests/test_cli.py:28: in <module>
    VALID_IOTHUBCONNECTIONSTRING = os.environ['IOTHUB_CONNECTION_STRING']
.tox/py27/lib/python2.7/UserDict.py:40: in __getitem__
    raise KeyError(key)
E   KeyError: 'IOTHUB_CONNECTION_STRING'

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
===================== 2 warnings, 1 error in 1.01 seconds ======================
ERROR: InvocationError for command /home/travis/build/Azure/iotedgehubdev/.tox/py27/bin/py.test -s --cov iotedgehubdev (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
The command "sudo `which tox`" exited with 1.
```

#### 3.7
```
______________________ ERROR collecting tests/test_cli.py ______________________
tests/test_cli.py:28: in <module>
    VALID_IOTHUBCONNECTIONSTRING = os.environ['IOTHUB_CONNECTION_STRING']
.tox/py37/lib/python3.7/os.py:678: in __getitem__
    raise KeyError(key) from None
E   KeyError: 'IOTHUB_CONNECTION_STRING'

=========================== short test summary info ============================
ERROR tests/test_cli.py - KeyError: 'IOTHUB_CONNECTION_STRING'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 2 warnings, 1 error in 0.92s =========================
ERROR: InvocationError for command /home/travis/build/Azure/iotedgehubdev/.tox/py37/bin/py.test -s --cov iotedgehubdev (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   py37: commands failed
The command "sudo `which tox`" exited with 1.
```

Any reason these fail based on a README change?

Thanks
Alex.

**Comment by SLdragon** [comment]
Thank you @AMCN41R, maybe it is an occasional error

**Comment by SLdragon** [comment]
Seems something wrong with the ci environment, I will try to fix it

**Comment by SLdragon** [comment]
Hi, @AMCN41R, could you please add a line to tox.ini file to fix the ci issue, thank you!

```
[flake8]
ignore=E741,E302

```

**Comment by SLdragon** [comment]
So bad, only this pull request always failed, not sure what's wrong with it....
Hi, @AMCN41R, could you please recreate another pull request for this, sorry for the inconvenience.

**Comment by AMCN41R** [comment]
Yeah, absolutely. That's no problem. I was thinking the same thing. Will create a new PR.

Thanks.

**Pull request closed without merging**
