### PR TITLE
Replace deprecated azure-cli-iot-ext with azure-iot

### PR DESCRIPTION
**Pull request by marianan**
This PR replaces the deprecated azure-cli-iot-ect with the latest azure-iot.

To validate:
1. Local environment:
a. in a Windows environment, install legacy extension, run all unit tests and make sure they pass [baseline]
b. In same environment, uninstall legacy extension, install latest extension, restart machine, run all unit tests and make sure they pass [baseline]
2. Pipeline:
a. Run iotedgehubdev pipeline on latest released tag https://dev.azure.com/mseng/VSIoT/_build?definitionId=7735 
b. Run iotedgehubdev pipeline on branch with changes and make sure all validation pass.
c. Run Travis pipeline on changes to confirm no issues https://travis-ci.org/github/Azure/iotedgehubdev

### CODE REVIEW

**Comment by smcd253** [comment]
Do the environment variables change when updating the extension? It seems as though the new version of the cli can't reach the endpoints given to it in the pipeline.

**Comment by marianan** [comment]
@Narsingh<mailto:v-nasadu@microsoft.com> helped me here; likely the Azure resources no longer exist or are not reachable. I will confirm this and will create a new set of resources in our new subscription so we can manage them moving forward.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by smcd253** [comment]
Can confirm that this PR successfully ran on ADO in a manual run after endpoints were updated.

**Review by smcd253 — APPROVED** [review]
Looks good to me! ADO pipeline was successful on manual run with updated endpoints.

**Comment by marianan** [comment]
Need to open a new PR so that the updates on the pipelines take effect.

**Pull request closed without merging**
