### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by AMCN41R**
Updated `README.md` formatting and content to improve readability.

### CODE REVIEW

**Comment by AMCN41R** [comment]
Hey @SLdragon,

Looks like it could be an issue with environment variables in the travis pipeline?

The error...
```
______________________ ERROR collecting tests/test_cli.py ______________________
tests/test_cli.py:28: in <module>
    VALID_IOTHUBCONNECTIONSTRING = os.environ['IOTHUB_CONNECTION_STRING']
.tox/py27/lib/python2.7/UserDict.py:40: in __getitem__
    raise KeyError(key)
E   KeyError: 'IOTHUB_CONNECTION_STRING'
```

I added a step to the travis config to print env vars, and there is no `IOTHUB_CONNECTION_STRING`, where should these be set?

I notice in `tests/__init__.py` it tries to load a `.env` file. Is that missing here?

**Comment by SLdragon** [comment]
Hi, @AMCN41R , I think the reason is that we have some encrypted envs, and in order to protect these envs, travis disabled them when pull request created from the other repo.

So I help you created another pull request for this to solve the problem: https://github.com/Azure/iotedgehubdev/pull/278

**Comment by AMCN41R** [comment]
Hey @SLdragon, that's great, thanks!

I'll go ahead and close this one.

**Comment by SLdragon** [comment]
Thank you @AMCN41R , now your changes has been merged into master: https://github.com/Azure/iotedgehubdev/commit/e4b4f9e19c563567708c46b3c943a5f6cdb62beb

**Pull request closed without merging**
